### ISSUE TITLE
OnUpdate spam issue

### ISSUE THREAD

**Issue by OakTree42** [rabidninjawombat/CivilianPopulation#1]
```
        print("Update!");
```

This line is in the OnUpdate override in line 1715 of your class1.cs and it is spamming F2 logs if that dll is in use. There is a related (maybe?) spamming of the following: 

[LOG 12:15:03.302] Update!
[LOG 12:15:03.315] Update!
[LOG 12:15:03.315] [RESOURCES] Invalid flow mode: all
[LOG 12:15:03.316] [RESOURCES] Invalid flow mode: all
[LOG 12:15:03.316] [RESOURCES] Invalid flow mode: all
[LOG 12:15:03.316] [RESOURCES] Invalid flow mode: all
[LOG 12:15:03.317] [RESOURCES] No Implementation of GetHeatProduction in derived class

Not sure about the second half, but the first two are definitely from this mod. The spam is making it impossible to track down some other bugs I was trying to isolate. Hope you can find the source of the other 5 messages?

**Comment by rabidninjawombat** [comment]
Tracking down and isolating is right now. will get a fix deployed ASAP

**Comment by rabidninjawombat** [comment]
Got the Update! Messages gone,  tracking down the RESOURCES spam.  Its obviously related to the CivilianPopulation Resource,  (as it only happens on craft with it.)   Will track it down shortly :D 

Also while im knee deep in the code nipping out a few other things  that aren't needed.

**Comment by OakTree42** [comment]
Hope having the exact line for the first half helped. :D Let me know if I can help with anything else.

**Comment by rabidninjawombat** [comment]
Will upload fix tomorrow :)  Thank Oak!  (narrowed the issue down to 2 of the baseconverter classes)

**Comment by rabidninjawombat** [comment]
Oak,  sent you a dev copy of the plugin to test, if you get a chance, report back and let me know if the log Spam is fixed.    everything looks kosher now on my end. =

**Comment by rabidninjawombat** [comment]
Ok, looks like its fixed in the dev DLL closing this.
